---
- name: Install Healthbeat on Ubuntu servers
  hosts: all
  become: yes
  become_user: vunet
  tasks:
    - name: Transfer installer tar file to /tmp
      copy:
        src: {{path}}
        dest: /tmp/installer.tar

    - name: Extract installer tar on /opt
      unarchive:
        src: /tmp/installer.tar
        dest: /opt
        remote_src: yes

    - name: Change directory to ./healthbeat
      become: yes
      become_user: vunet
      shell: cd /opt/healthbeat

    - name: Run the install script
      become: yes
      become_user: vunet
      shell: bash ./install --quick

