---
- name: Install Healthbeat on Ubuntu servers
  hosts: all
  become: yes
  become_method: sudo
  become_user: "{{ user }}"
  tasks:
    - name: Transfer installer tar file to /tmp
      copy:
        src: "{{ tarfile_path }}"
        dest: "{{ installer_path }}"

    - name: Extract archive from /tmp to /opt
      unarchive:
        src: "{{ installer_path }}"
        dest: "{{ path }}"
        remote_src: yes
        mode: "unzip"

    - name: Change permissions of a install file
      file:
        path: "{{ path }}/lhealthbeat_linux_64/install"
        mode: '0755'

    - name: Run the install script
      shell: "./install --quick --installpath {{ path }} --setupinit"
      args:
        chdir: "{{ path }}/lhealthbeat_linux_64"
