---
- name: Install Healthbeat on Linux servers
  hosts: all
  become: yes
  become_user: vunet
  tasks:
    - name: Ensure /opt directory exists
      file:
        path: /opt
        state: directory
        mode: '0755'
    
    - name: Copy file from Ansible control node to remote hosts
      ansible.builtin.shell:
        cmd: cp /home/vunet/lhealthbeat_linux_64.zip /tmp/lhealthbeat_linux_64.zip
      delegate_to: localhost

    - name: Copy file to remote hosts
      ansible.builtin.copy:
        src: "/tmp/lhealthbeat_linux_64.zip"
        dest: "/tmp/lhealthbeat_linux_64.zip"
        mode: '0644'



    - name: Extract installer tar file to /opt
      unarchive:
        src: /tmp/lhealthbeat_linux_64.zip
        dest: /opt

    - name: Run the Healthbeat installer
      command: bash ./install --quick --setupinit
      args:
        chdir: /opt/lhealthbeat_linux_64
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"
