---
- name: Install Healthbeat on Ubuntu servers
  hosts: all
  become: yes
  become_user: vunet
  tasks:
    - name: Transfer installer tar file to /tmp
      copy:
        src: "{{ path }}"
        dest: "/tmp/installer.tar"
        remote_src: yes

    - name: Extract installer tar on /opt
      shell: "tar -xf /tmp/installer.tar -C /opt && chown -R vunet:vunet /opt"

    - name: Change directory to ./healthbeat and run the install script
      shell: "cd /opt/healthbeat_linux_64_install && ./install --quick --setupinit"
