---
- name: Install Healthbeat on Ubuntu servers
  hosts: all
  become: yes
  become_user: "{{ user }}"
  tasks:
    - name: Transfer installer tar file to /tmp
      copy:
        src: "{{ tarfile_path }}"
        dest: "{{ installer_path }}"

    - name: Extract installer tar on /opt
      shell: "tar -xf {{installer_path}} -C {{path}} && chown -R vunet:vunet {{path}}"

    - name: Change directory to ./healthbeat
      shell: "cd {{path}}/healthbeat_linux_64_install"

    - name: Set execute permission for install script
      shell: "chmod +x ./install"
      args:
        chdir: "{{path}}/healthbeat_linux_64_install"

    - name: Run the install script
      shell: "./install --quick --setupinit"
      args:
        chdir: "{{path}}/healthbeat_linux_64_install"
