---
- name: Install Healthbeat on Ubuntu servers
  hosts: all
  become: yes
  become_method: sudo
  become_user: "{{ user }}"
  tasks:
    - name: Transfer installer tar file to /tmp
      copy:
        src: "{{ tarfile_path }}"
        dest: "{{ installer_path }}"

    - name: Extract archive from /tmp to /opt
      unarchive:
        src: "{{ installer_path }}"
        dest: "{{ path }}"
        remote_src: yes
        mode: "unzip"

    - name: Change permissions of a install file
      file:
        path: "{{ path }}/healthbeat_linux_64/install"
        mode: '0755'

    - name: Run the install script
      shell: "./install --quick --installpath {{ path }} --enablessl"
      args:
        chdir: "{{ path }}/healthbeat_linux_64"

    - name: Replace source_id to the current inventory host
      replace:
        path: "{{ path }}/healthbeat/etc/healthbeat/modules.d/linux.yml"
        regexp: '{HOST}'
        replace: "{{ ansible_host }}"

    - name: Replace kafka broker to vusmartmaps broker host IP or a valid fqdn dns name
      replace:
        path: "{{ path }}/healthbeat/etc/healthbeat/healthbeat.yml"
        regexp: 'localhost'
        replace: "{{ vunet_collector }}"
