---
- name: Install Healthbeat on Linux servers
  hosts: all
  become: yes
  become_user: vunet
  tasks:
    - name: Ensure /opt directory exists
      file:
        path: /opt
        state: directory
        mode: '0755'
    
    - name: Create temporary directory on Ansible control node
      ansible.builtin.file:
        path: "/tmp/ansible_temp"
        state: directory

    - name: Copy file to temporary directory on Ansible control node
      ansible.builtin.copy:
        src: "/home/vunet/lhealthbeat_linux_64.zip"
        dest: "/tmp/ansible_temp/lhealthbeat_linux_64.zip"

    - name: Synchronize file from temporary directory to /tmp on remote hosts
      synchronize:
        src: "/tmp/ansible_temp/"
        dest: "/tmp/"
        mode: pull
      delegate_to: localhost


    - name: Extract installer tar file to /opt
      unarchive:
        src: /tmp/lhealthbeat_linux_64.zip
        dest: /opt

    - name: Run the Healthbeat installer
      command: bash ./install --quick --setupinit
      args:
        chdir: /opt/lhealthbeat_linux_64
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"
