---
- name: Install Healthbeat on Ubuntu servers
  hosts: all
  become: yes
  become_user: vunet
  tasks:
    - name: Transfer installer tar file to /tmp
      become_user: vunet
      copy:
        src: "{{path}}"
        dest: "/tmp/installer.tar"
        remote_src: yes

    - name: Extract installer tar on /opt
      become: yes
      become_user: vunet
      unarchive:
        src: "/tmp/installer.tar"
        dest: "/home/vunet/"
        remote_src: yes

    - name: Change directory to ./healthbeat
      become: yes
      become_user: vunet
      shell: "cd /home/vunet/healthbeat_install"

    - name: Run the install script
      become: yes
      become_user: vunet
      shell: "bash ./install --quick --setupinit"

