---
- name: Install Healthbeat on Linux servers
  hosts: all
  become: yes
  become_user: vunet
  tasks:
    - name: Ensure /opt directory exists
      file:
        path: /opt
        state: directory
        mode: '0755'

    - name: Debugging Print current user
      ansible.builtin.debug:
        msg: "Current user is {{ ansible_user }}"

    - name: Debugging Print current effective user
      ansible.builtin.command: whoami
      register: result_whoami
      changed_when: false
      ignore_errors: true

    - name: Debugging  Print result of whoami command
      ansible.builtin.debug:
        var: result_whoami.stdout

    - name: Copy file to remote hosts
      ansible.builtin.copy:
        src: "/home/vunet/lhealthbeat_linux_64.zip"
        dest: "/tmp/lhealthbeat_linux_64.zip"
        remote_src: yes
      delegate_to: localhost

    - name: Extract installer tar file to /opt
      unarchive:
        src: /tmp/lhealthbeat_linux_64.zip
        dest: /opt

    - name: Run the Healthbeat installer
      command: bash ./install --quick --setupinit
      args:
        chdir: /opt/lhealthbeat_linux_64
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin"
